poker: poker.c score.c shuffle.s
		gcc -o poker poker.c score.c shuffle.s

test_shuffle: test_shuffle.c shuffle.s
		gcc -o test_shuffle test_shuffle.c shuffle.s

test_four_kind: test_four_kind.c score.c
		gcc -o test_four_kind test_four_kind.c score.c

test_full_house: test_full_house.c score.c
		gcc -o test_full_house test_full_house.c score.c

test_flush: test_flush.c score.c
		gcc -o test_flush test_flush.c score.c

test_straight: test_straight.c score.c
		gcc -o test_straight test_straight.c score.c

test_three_kind: test_three_kind.c score.c
		gcc -o test_three_kind test_three_kind.c score.c

test_two_pair: test_two_pair.c score.c
		gcc -o test_two_pair test_two_pair.c score.c

test_pair: test_pair.c score.c
		gcc -o test_pair test_pair.c score.c

test_ties: test_ties.c score.c
		gcc -o test_ties test_ties.c score.c