poker: poker.c score.c shuffle.s
		gcc -o poker poker.c score.c shuffle.s

test_shuffle: test_shuffle.c shuffle.s
		gcc -o test_shuffle test_shuffle.c shuffle.s

test_flush: test_flush.c score.c
		gcc -o test_flush test_flush.c score.c

test_four_kind: test_four_kind.c score.c
		gcc -o test_four_kind test_four_kind.c score.c